In [1]:
import uproot

### Samples
These ntuples were created using DHNLAlgorithm using all 10K events of
new: mc16_13TeV.311625.Pythia8EvtGen_A14NNPDF23LO_WmuHNL50_5G_lt100dd_el.recon.DAOD_RPVLL.e7660_e5984_a875_r11915
old: mc16_13TeV.311625.Pythia8EvtGen_A14NNPDF23LO_WmuHNL50_5G_lt100dd_el.merge.DAOD_RPVLL.e7660_e5984_a875_r10740_r10706

In [3]:
old_tree = uproot.open("/home/newhouse/public/Analysis/HNL/DHNLAlgorithm/run/testRun_old/data-tree/files_old.root")['outTree']
new_tree = uproot.open("/home/newhouse/public/Analysis/HNL/DHNLAlgorithm/run/testRun_new/data-tree/files_new.root")['outTree']

In [67]:
event_columns = [
'runNumber',
'eventNumber',
'lumiBlock',
'coreFlags',
'bcid',
'mcEventNumber',
'mcChannelNumber',
'mcEventWeight',
'NPV',
'actualInteractionsPerCrossing',
'averageInteractionsPerCrossing',
'passedTriggers',]

old_df = old_tree.pandas.df(event_columns).set_index(['lumiBlock'])
new_df = new_tree.pandas.df(event_columns).set_index(['lumiBlock'])

In [68]:
old_df.sort_index(inplace=True)
old_df

,runNumber,eventNumber,coreFlags,bcid,mcEventNumber,mcChannelNumber,mcEventWeight,NPV,actualInteractionsPerCrossing,averageInteractionsPerCrossing,passedTriggers
lumiBlock,,,,,,,,,,,
5,284500,5006,0,3120,5006,311625,1.0,6,4.5,4.5,[]
5,284500,3000,0,2103,3000,311625,1.0,5,4.5,4.5,[]
5,284500,4998,0,555,4998,311625,1.0,4,4.5,4.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
5,284500,3008,0,685,3008,311625,1.0,2,4.5,4.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
5,284500,8003,0,907,8003,311625,1.0,5,4.5,4.5,[]
...,...,...,...,...,...,...,...,...,...,...,...
45,284500,6002,0,2550,6002,311625,1.0,28,44.5,44.5,[]
45,284500,7008,0,2942,7008,311625,1.0,34,44.5,44.5,[]
45,284500,5997,0,1917,5997,311625,1.0,22,44.5,44.5,[]
45,284500,1,0,2340,1,311625,1.0,21,44.5,44.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
45,284500,4005,0,2768,4005,311625,1.0,23,44.5,44.5,[]

In [66]:
new_df.sort_index(inplace=True)
new_df

,runNumber,eventNumber,coreFlags,bcid,mcEventNumber,mcChannelNumber,mcEventWeight,NPV,actualInteractionsPerCrossing,averageInteractionsPerCrossing,passedTriggers
lumiBlock,,,,,,,,,,,
5,284500,4013,0,1467,4013,311625,1.0,3,4.5,4.5,[]
5,284500,3052,0,2047,3052,311625,1.0,2,4.5,4.5,[]
5,284500,49,0,2690,49,311625,1.0,3,4.5,4.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
5,284500,7916,0,2853,7916,311625,1.0,6,4.5,4.5,[]
5,284500,6985,0,3028,6985,311625,1.0,2,4.5,4.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
...,...,...,...,...,...,...,...,...,...,...,...
45,284500,8997,0,3261,8997,311625,1.0,24,44.5,44.5,[]
45,284500,1,0,2340,1,311625,1.0,21,44.5,44.5,"[b'HLT_mu24_ivarloose', b'HLT_mu24_iloose', b'..."
45,284500,4005,0,2550,4005,311625,1.0,24,44.5,44.5,[]
45,284500,1999,0,3290,1999,311625,1.0,28,44.5,44.5,[]
45,284500,7008,0,2284,7008,311625,1.0,25,44.5,44.5,[]

### Event number mismatch
It appears that the events used in the reprocessing are different at least for some lumiblocks.
In lumiblock 5-24 the mc event numbers do not match, but in lumiblock 25-45, there is a perfect match.
In each lumiblock, the number of events matches.

In [87]:
for i in set(new_df.index):
    print("lumiblock", i, "has", len(new_df.loc[i]), "events")
    if not len(new_df.loc[i]) == len(old_df.loc[i]): print("event count mismatch")
    print("event numbers match:", set(new_df.loc[i].eventNumber) == set(old_df.loc[i].eventNumber))
    print()

lumiblock 5 has 10 events
event numbers match: False

lumiblock 6 has 10 events
event numbers match: False

lumiblock 7 has 10 events
event numbers match: False

lumiblock 8 has 10 events
event numbers match: False

lumiblock 9 has 10 events
event numbers match: False

lumiblock 10 has 30 events
event numbers match: False

lumiblock 11 has 110 events
event numbers match: False

lumiblock 12 has 170 events
event numbers match: False

lumiblock 13 has 250 events
event numbers match: False

lumiblock 14 has 300 events
event numbers match: False

lumiblock 15 has 340 events
event numbers match: False

lumiblock 16 has 350 events
event numbers match: False

lumiblock 17 has 360 events
event numbers match: False

lumiblock 18 has 400 events
event numbers match: False

lumiblock 19 has 460 events
event numbers match: False

lumiblock 20 has 470 events
event numbers match: False

lumiblock 21 has 480 events
event numbers match: False

lumiblock 22 has 490 events
event numbers match: False

lumiblock 23 has 460 events
event numbers match: False

lumiblock 24 has 490 events
event numbers match: False

lumiblock 25 has 480 events
event numbers match: True

lumiblock 26 has 550 events
event numbers match: True

lumiblock 27 has 450 events
event numbers match: True

lumiblock 28 has 440 events
event numbers match: True

lumiblock 29 has 440 events
event numbers match: True

lumiblock 30 has 400 events
event numbers match: True

lumiblock 31 has 380 events
event numbers match: True

lumiblock 32 has 340 events
event numbers match: True

lumiblock 33 has 300 events
event numbers match: True

lumiblock 34 has 270 events
event numbers match: True

lumiblock 35 has 200 events
event numbers match: True

lumiblock 36 has 130 events
event numbers match: True

lumiblock 37 has 110 events
event numbers match: True

lumiblock 38 has 80 events
event numbers match: True

lumiblock 39 has 70 events
event numbers match: True

lumiblock 40 has 60 events
event numbers match: True

lumiblock 41 has 40 events
event numbers match: True

lumiblock 42 has 20 events
event numbers match: True

lumiblock 43 has 10 events
event numbers match: True

lumiblock 44 has 10 events
event numbers match: True

lumiblock 45 has 10 events
event numbers match: True

### No overlap in mismatched blocks
There is no overlap in event number for the unmatched lumiblocks.
This pattern is the same for all mismatched blocks.

In [88]:
# Mismatched block 5
print(new_df.loc[5].eventNumber.sort_values() , old_df.loc[5].eventNumber.sort_values())

lumiBlock
5      49
5    1060
5    2075
5    3052
5    4013
5    5011
5    6985
5    7916
5    8065
5    9055
Name: eventNumber, dtype: int64 lumiBlock
5     999
5    1002
5    3000
5    3008
5    4998
5    5006
5    6997
5    7993
5    8003
5    9007
Name: eventNumber, dtype: int64

In [90]:
# Matching block 45
print(new_df.loc[45].eventNumber.sort_values() , old_df.loc[45].eventNumber.sort_values())

lumiBlock
45       1
45    1999
45    2003
45    3996
45    4005
45    5997
45    6002
45    7008
45    8997
45    9995
Name: eventNumber, dtype: int64 lumiBlock
45       1
45    1999
45    2003
45    3996
45    4005
45    5997
45    6002
45    7008
45    8997
45    9995
Name: eventNumber, dtype: int64